workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      app_store_connect: tcelenkk@gmail.com  # buraya Apple ID mailini yaz
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Flutter build iOS
        script: |
          flutter packages pub get
          flutter build ios --release --no-codesign
      - name: Xcode build
        script: |
          xcode-project use-profiles
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - tcelenkk@gmail.com
      app_store_connect:
        submit_to_testflight: true
