workflows:
  ios-workflow:
    name: iOS Build & TestFlight
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      vars:
        APPLE_ID: tcelenkk@gmail.com
        APP_SPECIFIC_PASSWORD: lfih-fvic-ogmf-jfxn   # BURAYA 16 HANELİ ŞİFREYİ YAZ
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - flutter packages pub get
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - tcelenkk@gmail.com
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_SPECIFIC_PASSWORD
        submit_to_testflight: true
