name: iOS Build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: runner-app
          path: build/ios/iphoneos/Runner.app
